SIGNALS = {
    1: ('SIGHUP', 'kill', 'terminal line hangup'),
    2: ('SIGINT', 'kill', 'interrupt program'),
    3: ('SIGQUIT', 'core', 'quit program'),
    4: ('SIGILL', 'core', 'illegal instruction'),
    5: ('SIGTRAP', 'core', 'trace trap'),
    6: ('SIGABRT', 'core', 'abort program (formerly SIGIOT)'),
    7: ('SIGEMT', 'core', 'emulate instruction executed'),
    8: ('SIGFPE', 'core', 'floating-point exception'),
    9: ('SIGKILL', 'kill', 'kill program'),
    10: ('SIGBUS', 'core', 'bus error'),
    11: ('SIGSEGV', 'core', 'invalid memory reference'),
    12: ('SIGSYS', 'core', 'non-existent system call invoked'),
    13: ('SIGPIPE', 'kill', 'write on a pipe with no readers'),
    14: ('SIGALRM', 'kill', 'real-time timer expired'),
    15: ('SIGTERM', 'kill', 'software termination signal'),
    16: ('SIGURG', 'ignore', 'urgent condition present on socket'),
    17: ('SIGSTOP', 'stop', 'stop (cannot be caught or ignored)'),
    18: ('SIGTSTP', 'stop', 'stop signal generated from keyboard'),
    19: ('SIGCONT', 'ignore', 'continue after stop'),
    20: ('SIGCHLD', 'ignore', 'child status has changed'),
    21: ('SIGTTIN', 'stop', 'background read attempted from control terminal'),
    22: ('SIGTTOU', 'stop', 'background write attempted to control terminal'),
    23: ('SIGIO', 'ignore', 'I/O is possible on a descriptor'),
    24: ('SIGXCPU', 'kill', 'cpu time limit exceeded'),
    25: ('SIGXFSZ', 'kill', 'file size limit exceeded'),
    26: ('SIGVTALRM', 'kill', 'virtual time alarm'),
    27: ('SIGPROF', 'kill', 'profiling timer alarm'),
    28: ('SIGWINCH', 'ignore', 'Window size change'),
    29: ('SIGINFO', 'ignore', 'status request from keyboard'),
    30: ('SIGUSR1', 'kill', 'user defined signal 1'),
    31: ('SIGUSR2', 'kill', 'user defined signal 2'),
    32: ('SIGTHR',  'kill', 'thread interrupt'),
    33: ('SIGLIBRT','kill', 'real-time library interrupt'),
    }
